name = "Gallery (FORK)"
license = "BSD"
licenselink = "https://github.com/cneill/hugo-theme-gallery/blob/main/LICENSE"
description = "A gallery of _things_"
homepage = "https://github.com/cneill/hugo-theme-gallery"
tags = ["gallery", "responsive", "minimal", "dark"]
min_version = "0.121.2"

[author]
  name = "Charles Neill"
  homepage = "https://techiavellian.com"
